baseURL = "http://astro.luanguimaraes.me/"
languageCode = "pt-BR"
title = "Astronomia e Astrofísica"
theme = "paperesque"

[[params.topmenu]]
  name = "Sobre mim"
  url = "autor/"

[[params.menu]]
  name = "Artigos"
  url = "artigos/"

[[params.menu]]
  name = "Livros"
  url = "livros/"
