baseURL = "http://luanguimaraesla.github.io/astro-site/"
languageCode = "pt-BR"
title = "Astronomia e Astrofísica"
theme = "paperesque"
publishDir = "docs"

[[params.topmenu]]
  name = "Sobre mim"
  url = "autor/"

[[params.menu]]
  name = "Artigos"
  url = "artigos/"

[[params.menu]]
  name = "Livros"
  url = "livros/"
