baseURL = "http://astro.l2n.me/"
languageCode = "pt-BR"
title = "Astronomia e Astrofísica"
theme = "paperesque"
publishDir = "docs"

# support for comments
disqusShortname = "astro-luanguimaraes-me"

[[params.topmenu]]
  name = "Sobre mim"
  url = "autor/"

[[params.menu]]
  name = "Artigos"
  url = "artigos/"

[[params.menu]]
  name = "Livros"
  url = "livros/"
